import React from 'react';
import { Field, reduxForm } from 'redux-form';
import renderField from '../../../components/FormInputs/renderField';

const FormElements = () => (
  <div className="card">
    <div className="text-center header">
      <h4>Create Project</h4>
    </div>
    <div className="content">
      <form className="form-horizontal">
        <div className="form-group">
          <label className="control-label col-md-3">Country</label>
          <div className="col-md-9">
            <Field
              name="withHelp"
              type="text"
              component={renderField}
              placeholder="India"
            />
          </div>
        </div>

        <div className="form-group">
          <label className="control-label col-md-3">Client Name</label>
          <div className="col-md-9">
            <Field
              name="password"
              type="text"
              placeholder="Sample Client 1"
              component={renderField} />
          </div>
        </div>

        <div className="form-group">
          <label className="control-label col-md-3">Project Name</label>
          <div className="col-md-9">
            <Field
              name="placeholder"
              type="text"
              placeholder="Sample Project 1"
              component={renderField} />
          </div>
        </div>

        <div className="form-group">
          <label className="control-label col-md-3">Approver</label>
          <div className="col-md-9">
            <Field
              name="placeholder"
              type="text"
              placeholder="Approver name"
              component={renderField} />
          </div>
        </div>

        <div className="form-group">
          <label className="control-label col-md-3">Project Id</label>
          <div className="col-md-9">
            <Field
              name="disabled"
              type="text"
              placeholder="Auto Generated Id"
              disabled={true}
              component={renderField}
              helpText="Autogenerated on backend."
            />

          </div>
        </div>
      </form>

      <div className="buttons-with-margin text-center">

        <button type="button" className="btn btn-wd btn-info">
          <span className="btn-label">
          </span> Submit
        </button>
      </div>
    </div>
  </div>
);

export default reduxForm({
  form: 'formElements'
})(FormElements);
